[package]
name = "news-letter"
version = "0.1.0"
authors = ["Matt Woelfel <matt@woelfware.com>"]
edition = "2021"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.12.12"
